language:
    node_js

node_js:
    - "10"

branches:
    only:
        - master
        - /^greenkeeper/.*$/

cache:
    directories:
        - node_modules

script:
    - cd functions
    - yarn
    - yarn build
    - yarn test
