language:
    node_js

node_js:
    - "11"
    - "lts/*"

branches:
    only:
        - master
        - /^greenkeeper/.*$/

cache:
    directories:
        - node_modules

script:
    - cd functions
    - npm i -g bower
    - bower i
    - yarn
    - yarn build
    - yarn test
