language:
    node_js

node_js:
    - "9"

branches:
    only:
        - master
        - /^greenkeeper/.*$/

cache:
    directories:
        - node_modules

script:
    - cd functions
    - npm i -g bower
    - bower i
    - npm i
    - npm run build
    - npm test
